### ISSUE TITLE
pytubefix.exceptions.VideoPrivate: lVFj91Z1AfM is a private video for all video from Digital Ocean 

### ISSUE THREAD

**Issue by in4sec-org** [JuanBindez/pytubefix#119]
**Describe the bug**
I see `pytubefix.exceptions.VideoPrivate: SOME_ID is a private video` for all video from Digital Ocean Infra from this night. These are regular publicly available videos and not streams or live videos.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Python Version: python3.10
 - Pytubefix Version: Last release from github

**Additional context**
I have a small pet project, before I downloaded a maximum of 3-5 videos per day.

**Comment by potykion** [comment]
Same:
```
 (most recent call last):
  ...
  File "/function/code/apps/bot_tg_potyk.py", line 112, in download_yt_as_mp3
    yt.streams.filter(only_audio=True).order_by("abr").first().stream_to_buffer(buffer)
    ^^^^^^^^^^
  File "/function/code/pytubefix/__main__.py", line 564, in streams
    self.check_availability()
  File "/function/code/pytubefix/__main__.py", line 324, in check_availability
    raise exceptions.VideoPrivate(video_id=self.video_id)
pytubefix.exceptions.VideoPrivate:  [91mSpH83KzVKDc is a private video [0m
```

**Comment by JuanBindez** [comment]
try this version to see what error appears pytubefix==6.3.4rc1

**Comment by potykion** [comment]
> try this version to see what error appears pytubefix==6.3.4rc1

```
 (most recent call last):
  ...
  File "/function/code/apps/bot_tg_potyk.py", line 112, in download_yt_as_mp3
    yt.streams.filter(only_audio=True).order_by("abr").first().stream_to_buffer(buffer)
    ^^^^^^^^^^
  File "/function/code/pytubefix/__main__.py", line 534, in streams
    self.check_availability()
  File "/function/code/pytubefix/__main__.py", line 305, in check_availability
    raise exceptions.LoginRequired(video_id=self.video_id)
pytubefix.exceptions.LoginRequired:  [91mSpH83KzVKDc requires login to view [0m
```

**Comment by JuanBindez** [comment]
From my tests, it doesn't seem to be a problem with the library, it seems to be something with the video itself

**Comment by potykion** [comment]
Well it happens with any video that https://www.youtube.com/watch?v=K4TOrB7at0Y

```
 (most recent call last):
  ...t
  File "/function/code/apps/bot_tg_potyk.py", line 112, in download_yt_as_mp3
    yt.streams.filter(only_audio=True).order_by("abr").first().stream_to_buffer(buffer)
    ^^^^^^^^^^
  File "/function/code/pytubefix/__main__.py", line 534, in streams
    self.check_availability()
  File "/function/code/pytubefix/__main__.py", line 305, in check_availability
    raise exceptions.LoginRequired(video_id=self.video_id)
pytubefix.exceptions.LoginRequired:  [91mK4TOrB7at0Y requires login to view [0m
```

**Comment by JuanBindez** [comment]
![image](https://github.com/user-attachments/assets/6a5a8857-e1ec-43c2-8778-67289928bb51)

**Comment by JuanBindez** [comment]
Could you provide me with the complete code you are testing?

**Comment by potykion** [comment]
```python
from io import BytesIO

from pytubefix import YouTube

buffer = BytesIO()
(
    YouTube("https://www.youtube.com/watch?v=K4TOrB7at0Y")
    .streams
    .filter(only_audio=True)
    .order_by("abr")
    .first()
    .stream_to_buffer(buffer)
)
print(buffer.tell())
```

**Comment by potykion** [comment]
Well the code works on local environment, but it doesn't work on the cloud like Digital Ocean or Yandex Cloud

**Comment by felipeucelli** [comment]
YouTube may be [blocking your remote IP](https://github.com/yt-dlp/yt-dlp/issues/10128), try using `use_oauth` and let us know the results.

**Comment by JuanBindez** [comment]
> Well, the code works in the local environment, but it doesn't work in the cloud, such as Digital Ocean or Yandex Cloud

This may be the problem, as it is a cloud server there is no way of knowing the type of network infrastructure they have, there may be something in them that could cause blocking, due to their network infrastructure

**Comment by JuanBindez** [comment]
> Well, the code works in the local environment, but it doesn't work in the cloud, such as Digital Ocean or Yandex Cloud

try to do like @felipeucelli, but if it doesn't work I advise you to try to investigate their infrastructure from the inside to try to understand what is causing it.

**Comment by celarain** [comment]
Tryed rc version and says f14EJhG3X68 requires login to view, but I check in incognito mode without any user and video works

**Comment by potykion** [comment]
@felipeucelli @in4sec-org You were right. The problem was resolved when using oauth credentials. Thanks!

**Comment by celarain** [comment]
Can someone show all the code with the auth too please?

**Comment by potykion** [comment]
@celarain just pass `use_oauth=True` option like so:

```
YouTube(
    "https://www.youtube.com/watch?v=K4TOrB7at0Y",
    use_oauth=True,
)
```

**Comment by celarain** [comment]
I did that, then appear a url to auth my device, I did it and then gives me the error:

Error downloading video: EOF when reading a line

**Comment by potykion** [comment]
Well, check if `tokens.json` file was created in `pytubefix` installation directory e.g. `venv/Lib/site-packages/pytubefix/__cache__/tokens.json`

**Comment by celarain** [comment]
Send bad error report:

Please open https://www.google.com/device and input code FPA-HRL-WTR
Press enter when you have completed this step.2024-07-19 15:35:08,294 - app.video_downloader - ERROR - Error downloading video: EOF when reading a line

The problem is that I am connecting but if I try it again, it asks for the auth again
![image](https://github.com/user-attachments/assets/ecd16323-a072-43dd-90a6-6f2a67776c83)

**Comment by potykion** [comment]
Maybe your directory is not writable, but it's definitely not the problem with the lib. 

You can checkout the library code it should write `tokens.json` file to `pytubefix/__cache__` dir:
https://github.com/JuanBindez/pytubefix/blob/7e081b733074a7c030fdc18ea57ae5fb8c04ff17/pytubefix/innertube.py#L380C4-L394C1

**Comment by JuanBindez** [comment]
see the permissions of /var/www/ ll command and you may have to use chmod to change them

**Comment by celarain** [comment]
![image](https://github.com/user-attachments/assets/c947dd39-0077-45b1-bc8b-f72d1b2cdff9)

**Comment by celarain** [comment]
I am using pytubefix==6.3.4rc1 versión, which one should I use?

**Comment by JuanBindez** [comment]
this same one, from what I saw everyone has writing permission

**Comment by celarain** [comment]
the console log says after logging, then press continue, but I am reading this log with sudo journalctl -u socialmedia.service -f -n 30

And accepting permissions from external site, is that the problem? I have no idea how to do it in my external server everything

**Comment by celarain** [comment]
Thanks, will try it later!

**Comment by SuryanshuTiwari** [comment]
Hello All,

I got the same error, the code is working fine locally but when I deployed my code on heroku it game this error. I tried using use_oauth as well but it does not seems to be working.
![image](https://github.com/user-attachments/assets/eb15f444-5d3b-4163-b087-b3756e53871e)

I am using pytubefix==6.8.1. I tried downgrading the version as well as upgrading to the latest one but the error is still not fixed.

Any help is truly appreciated.

**Comment by iqbalcrat** [comment]
is this issue fixed?

**Comment by SubodaDabarera** [comment]
**Fixed the login required issue for an AWS EC2 deployed application.**

The problem was that it asked for authentication in EC2 after deployment when use_oauth=True was set, as mentioned by @felipeucelli and @potykion. Locally, it worked perfectly.

My local environment:

> OS : ubuntu 22.04  
Python : 3.10  
pytubefix : 6.6.2

The solution as below:

1. Use the local environment to authenticate with PytubeFix’s required authentication (use the given URL to log into your Google account and press Enter on the terminal). **Don't use your main google account**
2. Find the cached authentication credentials inside the PytubeFix library. Most likely, it will be located at `venv/lib/python3.10/site-packages/pytubefix/__cache__/tokens.json`
3. Open your AWS console, go to EC2 instances, and connect to the EC2 instance via the AWS terminal
4. Locate your project files and navigate to the `venv/lib/python3.10/site-packages/pytubefix` directory within your project.
5. If it doesn’t exist, create a directory named "\_\_cache__" (`mkdir __cache__`) inside the "pytubefix" directory and create a file called "tokens.json" (`touch tokens.json`) inside the "\_\_cache__" directory
6. Copy the contents of your **local** "tokens.json" file and paste them into the **EC2** "tokens.json" file. Use `nano tokens.json` to open the file, paste the code, save it, and exit
7. Restart the server via the AWS console or using supervisorctl

Now the issue is fixed, and videos are being extracted from YouTube without the “Login required” or “Private video” issues

But the problem is that it needs to update the tokens.json file when the OAuth token expires. Is there an alternative way of doing that?

Link - https://stackoverflow.com/questions/78959061/pytubefix-issue-handling-login-required-on-aws-ec2-deployed-applications

**Comment by felipeucelli** [comment]
@SubodaDabarera 
>But the problem is that it needs to update the tokens.json file when the OAuth token expires. Is there an alternative way of doing that?

YouTube is working tirelessly to block third-party apps. Update to the latest version of pytubefix and try:

1. You can create a custom function that works best in your environment and pass it using `oauth_verifier`, see #190.

2. You can also try to pass the PoToken which is valid for several days, see #209.
