### ISSUE TITLE
how to search something

### ISSUE THREAD

**Issue by Morteza820** [JuanBindez/pytubefix#162]
i want to search something in youtube and upload in  telegram
how?
 
i searched and received this :
[<pytubefix.__main__.YouTube object: videoId=dbjPnXaacAU>, <pytubefix.__main__.YouTube object: videoId=yhS9LnDoo_w>, <pytubefix.__main__.YouTube object: videoId=mOcR6-ocXO8>, <pytubefix.__main__.YouTube object: videoId=PK_EJ3DyiiA>, <pytubefix.__main__.YouTube object: videoId=9ll2_BDZpI4>, <pytubefix.__main__.YouTube object: videoId=07CQ6hiLnbk>, <pytubefix.__main__.YouTube object: videoId=e_QvTPNEXFQ>, <pytubefix.__main__.YouTube object: videoId=1Nrj6LsbINM>, <pytubefix.__main__.YouTube object: videoId=FsvJzfXZI18>, <pytubefix.__main__.YouTube object: videoId=NS0xBDFvUHs>, <pytubefix.__main__.YouTube object: videoId=KBCA3UfbOzI>, <pytubefix.__main__.YouTube object: videoId=iVbopWyBR5Y>, <pytubefix.__main__.YouTube object: videoId=2a4Uxdy9TQY>, <pytubefix.__main__.YouTube object: videoId=D4rYMM4L0KI>, <pytubefix.__main__.YouTube object: videoId=ijSYp6N5Yrs>, <pytubefix.__main__.YouTube object: videoId=MzUN2J3e1o0>, <pytubefix.__main__.YouTube object: videoId=TzS1rRWal5M>, <pytubefix.__main__.YouTube object: videoId=ScH9bCyqJ6s>, <pytubefix.__main__.YouTube object: videoId=VxcbppCX6Rk>, <pytubefix.__main__.YouTube object: videoId=qQFkur0FGWg>]

**Comment by daemosity** [comment]
Hi @Morteza820!

I'm not part of the pytubefix team, but saw your issue and wanted to offer some thoughts that could help you on your journey:

The issue described above shows output from using [pytubefix's Search](https://pytubefix.readthedocs.io/en/latest/user/search.html) and displaying the results, similar to the following code:

```python
from pytubefix import Search

# Search for something on YouTube
s = Search("Github Issue Best Practices")

# Display the captured results
s.results

# output: a List of pytubefix.YouTube objects and their videoIds
#
# [<pytubefix.main.YouTube object: videoId=dbjPnXaacAU> ...
# ... <pytubefix.main.YouTube object: videoId=qQFkur0FGWg>]
```

You can do a number of things with each [YouTube object](https://pytubefix.readthedocs.io/en/latest/api.html) by either iterating through the list or using a map function, but it doesn't appear as though this issue is actually a bug.

***If you're encountering an error or are receiving output different from what the [library documentation](https://pytubefix.readthedocs.io/en/latest/index.html) describes***, the best way to help the dev team resolve your bug is to give as much information as you can to help them understand what went wrong. A great way to do this is:

- After reading the [library documentation](https://pytubefix.readthedocs.io/en/latest/index.html) and comparing it to your experience:
  - Search the repo issues to make sure your issue hasn't already been addressed
  - Share the specific code you used, and the error (if any) or behavior you
  - Share (with a specific output example) the behavior/output you had expected
  - Include additional details that may help the devs figure out what went wrong ([This guide](https://www.contribution-guide.org/#submitting-bugs) mentions some good suggestions)

***If the issue you're having is how to use the library to accomplish a task/goal you have in mind***, searching for similar questions on [stackoverflow](https://stackoverflow.com/) and google can be helpful. If you can't find a similar question there, submitting your question on stackoverflow with appropriate tags (and with as much information as possible re: your intent, your code *stripped of all personal information*, your encountered outcome, and your desired outcome) will be your best bet for accomplishing your goal.

Good luck, and have fun with your project!

**Comment by JuanBindez** [comment]
example:

```python
>>> from pytubefix import Search
>>> 
>>> results = Search('Github Issue Best Practices')
>>> 
>>> for video in results.videos:
...     print(f'Title: {video.title}')
...     print(f'URL: {video.watch_url}')
...     print(f'Duration: {video.length} seg')
...     print('---')
... 
Title: Good Practices with GitHub Issues
URL: https://youtube.com/watch?v=v1AeHaopAYE
Duration: 406 seg
---
Title: GitHub Issues Tips and Guidelines
URL: https://youtube.com/watch?v=kezinXSoV5A
Duration: 852 seg
---
Title: 13 Advanced (but useful) Git Techniques and Shortcuts
URL: https://youtube.com/watch?v=ecK3EnyGD8o
Duration: 486 seg
---
Title: Managing a GitHub Organization Tools, Tips, and Best Practices - Mark Matyas
URL: https://youtube.com/watch?v=1T4HAPBFbb0
Duration: 1525 seg
---
Title: Do you know the best way to manage GitHub Issues?
URL: https://youtube.com/watch?v=OccRyzAS4Vc
Duration: 534 seg
---
Title: Git Best Practices - I Wish I Would Learn Them Sooner
URL: https://youtube.com/watch?v=ThiINH4DV6Q
Duration: 610 seg
---
Title: How to Use GitHub Issues and Milestones to Plan a Project
URL: https://youtube.com/watch?v=0Cab2islg0A
Duration: 1243 seg
---
Title: Level up your GitHub Issues
URL: https://youtube.com/watch?v=hNs5Gg_fEEs
Duration: 499 seg
---
Title: Git and GitHub Tutorials #5 - Understanding GitHub Issues
URL: https://youtube.com/watch?v=TKJ4RdhyB5Y
Duration: 397 seg
---
Title: AVOID THESE! - Follow The Quartz NET Listener Best Practices
URL: https://youtube.com/watch?v=e7U56HiZ67s
Duration: 756 seg
---
Title: GitHub Crash Course Responding to Code Reviews
URL: https://youtube.com/watch?v=vSsUO_OP-f8
Duration: 320 seg
---
Title: Contributing to Open Source Can Change Your Life - Here’s How to Do It
URL: https://youtube.com/watch?v=CML6vfKjQss
Duration: 197 seg
---
Title: Git for Professionals Tutorial - Tools & Concepts for Mastering Version Control with Git
URL: https://youtube.com/watch?v=Uszj_k0DGsg
Duration: 2442 seg
---
Title: 10 GitHub Best Practices for repository management
URL: https://youtube.com/watch?v=VvgoOgWFiZY
Duration: 599 seg
---
Title: Why are you being such a git about it? - Git Best Practices
URL: https://youtube.com/watch?v=AN-iaHcXgYI
Duration: 1640 seg
---
Title: Git for Beginners Best Practices for Teams (Part 7)
URL: https://youtube.com/watch?v=Hd_BMpn4sBA
Duration: 661 seg
---
Title: How GitHub Actions 10x my productivity
URL: https://youtube.com/watch?v=yfBtjLxn_6k
Duration: 498 seg
---
Title: What is GitHub Issues?
URL: https://youtube.com/watch?v=6HWw7rhwvtY
Duration: 50 seg
---
Title: Best practices for securing GitHub in the cloud - Universe 2022
URL: https://youtube.com/watch?v=Z5AKsVdZijE
Duration: 662 seg
---
Title: GitHub Security Best Practices - GitHub Universe 2015
URL: https://youtube.com/watch?v=0MQihfI_OMA
Duration: 1999 seg
---
>>> 


```

**Comment by JuanBindez** [comment]
https://pytubefix.readthedocs.io/en/latest/user/search.html
