### ISSUE TITLE
[SUPPORT] Save audio in MP3 seems to be in M4A

### ISSUE THREAD

**Issue by sukhoi47** [JuanBindez/pytubefix#2]
Hi,

I am testing  pytubefix 1.3, running it with python 3.9 in Windows environment.

I did the download of a file in MP3 format with this code:
```
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = 'http://youtube.com/watch?v=Eh8lFEzMMXA'
yt = YouTube(url, on_progress_callback=on_progress)
print(yt.title)
ys = yt.streams.get_audio_only()  # use this method -> get_audio_only()
ys.download(mp3=True)  # pass the parameter mp3=True to save in .mp3
```

It did the download of the file as expected and saved it with .MP3 extension, however the file seems to be in M4A audio format, rather than MP3 (according to VLC Player):

![test_mp3](https://github.com/JuanBindez/pytubefix/assets/22125794/87ac1e94-17d4-4d5f-82cf-62258598b5f3)

Am I missing something to get a real MP3 file?

**Comment by JuanBindez** [comment]
> Oi,
> 
> Estou testando o pytubefix 1.3, executando-o com python 3.9 em ambiente Windows.
> 
> Fiz o download de um arquivo em formato MP3 com este código:
> 
> ```
> from pytubefix import YouTube
> from pytubefix.cli import on_progress
> 
> url = 'http://youtube.com/watch?v=Eh8lFEzMMXA'
> yt = YouTube(url, on_progress_callback=on_progress)
> print(yt.title)
> ys = yt.streams.get_audio_only()  # use this method -> get_audio_only()
> ys.download(mp3=True)  # pass the parameter mp3=True to save in .mp3
> ```
> 
> Ele fez o download do arquivo conforme o esperado e o salvou com extensão .MP3, porém o arquivo parece estar no formato de áudio M4A, ao invés de MP3 (de acordo com o VLC Player):
> 
> ![test_mp3](https://user-images.githubusercontent.com/22125794/272111491-87ac1e94-17d4-4d5f-82cf-62258598b5f3.jpg)
> 
> Am I missing something to get a real MP3 file?

hello sukhoi47 how are you?, yes you are right, pytubefix only renames audios with .mp3 so that they can be identified by smartphones more easily instead of having to manually rename them, and another thing is that MP4A (also known as AAC) : It is an audio format based on the AAC (Advanced Audio Coding) codec, which is a more modern and efficient audio compression standard. AAC offers better audio quality than MP3 at lower bitrates and is widely used on modern devices such as smartphones, tablets and music streaming services. And if pytubefix is ​​going to do the actual conversion we will have to use third party libraries and this we want to avoid, if you have a suggestion on how to convert without using third party libraries feel free to make a PR, it will be a pleasure to merge.

**Comment by JuanBindez** [comment]
> Hi,
> 
> I am testing pytubefix 1.3, running it with python 3.9 in Windows environment.
> 
> I did the download of a file in MP3 format with this code:
> 
> ```
> from pytubefix import YouTube
> from pytubefix.cli import on_progress
> 
> url = 'http://youtube.com/watch?v=Eh8lFEzMMXA'
> yt = YouTube(url, on_progress_callback=on_progress)
> print(yt.title)
> ys = yt.streams.get_audio_only()  # use this method -> get_audio_only()
> ys.download(mp3=True)  # pass the parameter mp3=True to save in .mp3
> ```
> 
> It did the download of the file as expected and saved it with .MP3 extension, however the file seems to be in M4A audio format, rather than MP3 (according to VLC Player):
> 
> ![test_mp3](https://user-images.githubusercontent.com/22125794/272111491-87ac1e94-17d4-4d5f-82cf-62258598b5f3.jpg)
> 
> Am I missing something to get a real MP3 file?

hello sukhoi47 how are you?, yes you are right, pytubefix only renames audios with .mp3 so that they can be identified by smartphones more easily instead of having to manually rename them, and another thing is that MP4A (also known as AAC) : It is an audio format based on the AAC (Advanced Audio Coding) codec, which is a more modern and efficient audio compression standard. AAC offers better audio quality than MP3 at lower bitrates and is widely used on modern devices such as smartphones, tablets and music streaming services. And if pytubefix is ​​going to do the actual conversion we will have to use third party libraries and this we want to avoid, if you have a suggestion on how to convert without using third party libraries feel free to make a PR, it will be a pleasure to merge
